# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
)

platform :ios do
 desc "Download certificates from the git"
    lane :syncCertificates do
        match(
            api_key: api_key,
            type: "appstore"
         )
        match(
           api_key: api_key,
           type: "development"
       )
    end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    if ENV['CI']
        create_keychain(
            name: ENV["TEMP_KEYCHAIN_USER"],
            password: ENV["MATCH_PASSWORD"],
            default_keychain: true,
            unlock: true,
            timeout: 3600,
            lock_when_sleeps: false
        )

        match(
            keychain_name: ENV["TEMP_KEYCHAIN_USER"],
            api_key: api_key,
            type: "appstore",
         )
    end
    increment_build_number({ build_number: latest_testflight_build_number + 1 })
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", xcodebuild_formatter: "" )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
  desc "Push a new beta build to TestFlight"
  lane :build do
    if ENV['CI']
        create_keychain(
            name: ENV["TEMP_KEYCHAIN_USER"],
            password: ENV["MATCH_PASSWORD"],
            default_keychain: true,
            unlock: true,
            timeout: 3600,
            lock_when_sleeps: false
        )

        match(
            keychain_name: ENV["TEMP_KEYCHAIN_USER"],
            api_key: api_key,
            type: "appstore",
         )
    end
    increment_build_number({ build_number: latest_testflight_build_number + 1 })
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", xcodebuild_formatter: "" )
  end
end
