name: Build IOS

on:
  push:
    branches:
      - dev
      - master
jobs:
  build_ios:
    name: Build IOS
    runs-on: macos-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v2
      - run: echo "hello world"
